import { MenuBag } from '@app/shared/_models';
import { PermissionsEnum } from '@app/shared/_models/menu/permissions.enum';

export const appModules: MenuBag[] = [
    {
        uuid: 'EMR',
        title: 'Medical Records Section',
        linkTitle: 'Medical Records',
        icon: 'fa fa-bed',
        hierarchy: 1,
        permissions: [
            {
                title: 'Register A Patient',
                linkTitle: 'Register New Patient',
                url: '/emr/patient-registration',
                uuid: 1,
                right: PermissionsEnum.Emr_Patient_Registration,
                hierarchy: 1,
            },
            {
                title: 'Update A Patient',
                linkTitle: 'Edit Patient Details',
                url: '/emr/patient-edit',
                uuid: 2,
                right: PermissionsEnum.Emr_Edit_Patient_Details,
                hierarchy: 2,
            },
            {
                title: 'Revisit A Patient',
                linkTitle: 'View Patient Revisit Record',
                url: '/emr/patient-revisit',
                uuid: 3,
                right: PermissionsEnum.Emr_Record_Visit,
                hierarchy: 3,
            },
            {
                title: 'Move A Patient Folder',
                linkTitle: 'Manage Patient Category',
                url: '/emr/patient-category',
                uuid: 4,
                right: PermissionsEnum.Emr_Patient_Folder_Movement,
                hierarchy: 4,
            },
            {
                title: 'Change A Patient Category ',
                linkTitle: 'Patient Category Management',
                url: '/emr/patient-category-management',
                uuid: 5,
                right: PermissionsEnum.Emr_Patient_Category_Management,
                hierarchy: 5,
            },
            {
                title: 'Add / Edit Scheme',
                linkTitle: 'Scheme Manager',
                url: '/emr/scheme-manager',
                uuid: 6,
                right: PermissionsEnum.Emr_Edit_Scheme_Details,
                hierarchy: 6,
            },
            {
                title: ' Admit A Patient',
                linkTitle: 'Update Patient Scheme Details',
                url: '/emr/patient-admission',
                uuid: 7,
                right: PermissionsEnum.Emr_Patient_Admission,
                hierarchy: 7,
            },
            {
                title: 'Admission Details',
                linkTitle: 'Admission Details',
                url: '/emr/admission-details',
                uuid: 8,
                right: PermissionsEnum.Emr_Admission_Details,
                hierarchy: 8,
            },
            {
                title: 'Move Patient To New Ward',
                linkTitle: 'Patient Ward Transfer Manager',
                url: '/emr/patient-ward-transfer',
                uuid: 9,
                right: PermissionsEnum.Emr_Ward_Transfer,
                hierarchy: 9,
            },
            {
                title: 'Control Indexing | Coding',
                linkTitle: 'Indexing | Coding',
                url: '/emr/patient-coding-indexing',
                uuid: 10,
                right: PermissionsEnum.Emr_Coding_and_Indexing,
                hierarchy: 10,
            },
            {
                title: 'Book Appointment',
                linkTitle: 'Appointment Booking',
                url: '/emr/patient-appointment-booking',
                uuid: 11,
                right: PermissionsEnum.Emr_Appointment_Booking,
                hierarchy: 11,
            },
            {
                title: 'Control Clinical Attendance ',
                linkTitle: 'Control Clinical Attendance',
                url: '/emr/clinic-attendance',
                uuid: 12,
                right: PermissionsEnum.Emr_Clinical_Attendance,
                hierarchy: 12,
            },
            {
                title: 'Register Dead Patient',
                linkTitle: 'Register A Dead Patient',
                url: '/emr/death-register',
                uuid: 13,
                right: PermissionsEnum.Emr_Death_Register,
                hierarchy: 13,
            },
            {
                title: 'Discharge Patient',
                linkTitle: 'Discharge A Patient',
                url: '/emr/patient-discharge',
                uuid: 14,
                right: PermissionsEnum.Emr_Patient_Discharge,
                hierarchy: 14,
            },
            {
                title: 'Control Approval Codes',
                linkTitle: 'Control Approval Codes',
                url: '/emr/approval-code-office',
                uuid: 15,
                right: PermissionsEnum.Emr_Approval_Code_Office,
                hierarchy: 15,
            },
            {
                title: 'Register New Born',
                linkTitle: 'Register A New Born',
                url: '/emr/birth-register',
                uuid: 16,
                right: PermissionsEnum.Emr_Birth_Register,
                hierarchy: 16,
            },
            {
                title: 'Patient Search Index',
                linkTitle: 'Patient Search Index',
                url: '/emr/patient-search-index',
                uuid: 17,
                right: PermissionsEnum.Emr_Patient_Search_Index,
                hierarchy: 17,
            },
            {
                title: 'Change An Organization Info',
                linkTitle: 'Change An Organization Info',
                url: '/emr/edit-organization-details',
                uuid: 18,
                right: PermissionsEnum.Emr_Edit_Organization_Details,
                hierarchy: 18,
            },
            {
                title: 'Appointment Booking Setting',
                linkTitle: 'Appointment Booking Setting',
                url: '/emr/appointment-booking-setup',
                uuid: 19,
                right: PermissionsEnum.Emr_Appointment_Booking_Setup,
                hierarchy: 19,
            },
        ],
    },

    {
        uuid: 'Pharmacy',
        title: 'Pharmacy Section',
        linkTitle: 'Pharmacy Billing Section ',
        icon: 'fa fa-medkit',
        hierarchy: 2,
        permissions: [
            {
                uuid: 19,
                title: 'Register Drugs',
                linkTitle: 'Drug Register',
                url: '/pharmacy/drug-register',
                right: PermissionsEnum.Pharmacy_Drug_Register,
                hierarchy: 1,
            },
            {
                uuid: 20,
                title: 'Bill A Patient',
                linkTitle: 'Bill A Patient',
                url: '/pharmacy/drug-billing',
                right: PermissionsEnum.Pharmacy_Pharmacy_Billing,
                hierarchy: 2,
            },
            {
                uuid: 21,
                title: 'Drug Order Level',
                linkTitle: 'Drug Order Level',
                url: '/pharmacy/drug-order',
                right: PermissionsEnum.Pharmacy_Drug_Order,
                hierarchy: 3,
            },
            {
                uuid: 22,
                title: 'Receive Goods From Suppliers',
                linkTitle: 'Receive Goods From Suppliers',
                url: '/pharmacy/receive-goods-from-suppliers',
                right: PermissionsEnum.Pharmacy_Receive_Goods_From_Suppliers,
                hierarchy: 4,
            },
            {
                uuid: 23,
                title: 'Outlet Reconciliation',
                linkTitle: 'Outlet Reconciliation',
                url: '/pharmacy/outlet-reconciliation',
                right: PermissionsEnum.Pharmacy_Outlet_Reconciliation,
                hierarchy: 5,
            },
            {
                uuid: 24,
                title: 'Store Reconciliation',
                linkTitle: 'Store Reconciliation',
                url: '/pharmacy/store-reconciliation',
                right: PermissionsEnum.Pharmacy_Store_Reconciliation,
                hierarchy: 6,
            },
            {
                uuid: 25,
                title: 'To Store Requisition',
                linkTitle: 'To Store Requisition',
                url: '/pharmacy/to-store-requisition',
                right: PermissionsEnum.Pharmacy_To_Store_Requisition,
                hierarchy: 7,
            },
            {
                uuid: 26,
                title: 'To Outlet Requisition',
                linkTitle: 'To Outlet Requisition',
                url: '/pharmacy/to-outlet-requisition',
                right: PermissionsEnum.Pharmacy_To_Outlet_Requisition,
                hierarchy: 8,
            },
            {
                uuid: 27,
                title: 'Store Issuance',
                linkTitle: 'Store Issuance',
                url: '/pharmacy/store-issuance',
                right: PermissionsEnum.Pharmacy_Store_Issuance,
                hierarchy: 9,
            },
            {
                uuid: 28,
                title: 'Outlet Issuance',
                linkTitle: 'Outlet Issuance',
                url: '/pharmacy/outlet-issuance',
                right: PermissionsEnum.Pharmacy_Outlet_Issuance,
                hierarchy: 10,
            },
            {
                uuid: 29,
                title: 'Dispense Drugs',
                linkTitle: 'Dispense Drug',
                url: '/pharmacy/drug-dispensing',
                right: PermissionsEnum.Pharmacy_Drug_Dispensing,
                hierarchy: 11,
            },
            {
                uuid: 30,
                title: 'Dispense Drugs In Batch',
                linkTitle: 'Dispense Drugs In Batch',
                url: '/pharmacy/batch-drug-dispensing',
                right: PermissionsEnum.Pharmacy_Batch_Drug_Dispensing,
                hierarchy: 12,
            },
            {
                uuid: 31,
                title: 'Withdraw Drugs',
                linkTitle: 'Withdraw Drugs',
                url: '/pharmacy/drug-withdrawals',
                right: PermissionsEnum.Pharmacy_Drug_Withdrawals,
                hierarchy: 13,
            },
            {
                uuid: 32,
                title: 'Return Drugs From Patient',
                linkTitle: 'Return Drugs From Patient',
                url: '/pharmacy/patient-drug-return',
                right: PermissionsEnum.Pharmacy_Patient_Drug_Return,
                hierarchy: 14,
            },
            {
                uuid: 33,
                title: 'Note Drug Return',
                linkTitle: 'Note Drug Return ',
                url: '/pharmacy/drug-return-note',
                right: PermissionsEnum.Pharmacy_Drug_Return_Note,
                hierarchy: 15,
            },
            {
                uuid: 34,
                title: 'Private Wing Pharmacy Billing',
                linkTitle: 'Private Wing Pharmacy Billing',
                url: '/pharmacy/private-wing',
                right: PermissionsEnum.Pharmacy_Private_Wing_Pharmacy_Billing,
                hierarchy: 16,
            },
            {
                uuid: 35,
                title: 'Executive Wing Pharmacy Billing',
                linkTitle: 'Executive Wing Pharmacy Billing',
                url: '/pharmacy/executive-wing',
                right: PermissionsEnum.Pharmacy_Executive_Wing_Pharmacy_Billing,
                hierarchy: 17,
            },
            {
                uuid: 235,
                title: 'Pharmacy Notification ',
                linkTitle: 'Pharmacy Store/Outlet Notification',
                url: '/pharmacy/store-outlet-notifications',
                right: PermissionsEnum.Pharmacy_Pharmacy_Notifications,
                hierarchy: 18,
            },
        ],
    },

    {
        uuid: 'Billing',
        linkTitle: 'Billing & Payment Section',
        icon: 'fa fa-shopping-cart',
        title: 'Billing & Payment',
        hierarchy: 3,
        permissions: [
            {
                uuid: 36,
                title: 'Bill A Regular Patient',
                linkTitle: 'Bill A Regular Patient',
                url: '/billing/bill-general-patient',
                right: PermissionsEnum.Billing_Patient_Billing,
                hierarchy: 1,
            },
            {
                uuid: 37,
                title: 'Bill A Scheme Patient',
                linkTitle: 'Bill A Scheme Patient',
                url: '/billing/bill-scheme-patient',
                right: PermissionsEnum.Billing_Patient_Scheme_Billing,
                hierarchy: 2,
            },
            {
                uuid: 38,
                title: 'Adjust A Bill',
                linkTitle: 'Adjust A Bill',
                url: '/billing/adjust-bill',
                right: PermissionsEnum.Billing_Bill_Adjustment,
                hierarchy: 3,
            },
            {
                uuid: 39,
                title: 'Make Payment',
                linkTitle: 'Make Payment For Bills',
                url: '/billing/make-payment',
                right: PermissionsEnum.Billing_Payment_Manager,
                hierarchy: 4,
            },
            {
                uuid: 40,
                title: 'Pay Deposit',
                linkTitle: 'Make Patient Deposit',
                url: '/billing/pay-deposit',
                right: PermissionsEnum.Billing_Patient_Deposit,
                hierarchy: 5,
            },
            {
                uuid: 41,
                title: 'Waive A Bill',
                linkTitle: 'Bill Waivers',
                url: '/billing/waive-bill',
                right: PermissionsEnum.Billing_Bill_Waivers,
                hierarchy: 6,
            },
            {
                uuid: 42,
                title: 'Cancel A Receipt',
                linkTitle: 'Cancel A Receipt',
                url: '/billing/cancel-receipt',
                right: PermissionsEnum.Billing_Receipt_Cancellation,
                hierarchy: 7,
            },
            {
                uuid: 43,
                title: 'Hmo Billing',
                linkTitle: 'Receipt Cancellation',
                url: '/billing/hmo-billing',
                right: PermissionsEnum.Billing_Hmo_Billing,
                hierarchy: 8,
            },
            {
                uuid: 44,
                title: 'Ret. Organization Billing',
                linkTitle: 'Receipt Cancellation',
                url: '/billing/organization-billing',
                right: PermissionsEnum.Billing_Ret_Organization_Billing,
                hierarchy: 9,
            },
            {
                uuid: 45,
                title: 'Scheme Bill Adjustment',
                linkTitle: 'Scheme Bill Adjustment',
                url: '/billing/adjust-scheme-bill',
                right: PermissionsEnum.Billing_Scheme_Bill_Adjustment,
                hierarchy: 10,
            },
            {
                uuid: 46,
                title: 'Make Refunds',
                linkTitle: 'Make Refunds',
                url: '/billing/payment-refunds',
                right: PermissionsEnum.Billing_Refund,
                hierarchy: 11,
            },
            {
                uuid: 47,
                title: 'Transfer A Patient Deposit',
                linkTitle: 'Transfer A Patient Deposit',
                url: '/billing/transfer-deposit',
                right: PermissionsEnum.Billing_Patient_Deposit_Transfer,
                hierarchy: 12,
            },
        ],
    },

    {
        uuid: 'ShiftManagement',
        title: 'Shift Control',
        linkTitle: 'Shift Control Section',
        icon: 'fa fa-clock',
        hierarchy: 4,
        permissions: [
            {
                uuid: 48,
                title: 'Shift Manager',
                linkTitle: 'Shift Manager',
                url: '/shift/shift-manager',
                right: PermissionsEnum.ShiftManagement_Shift_Manager,
                hierarchy: 1,
            },
            {
                uuid: 49,
                title: 'Cashier Shift Report',
                linkTitle: 'Cashier Shift Report Manager',
                url: '/shift/cashier-shift',
                right: PermissionsEnum.ShiftManagement_Cashier_Shift_Report,
                hierarchy: 2,
            },
            {
                uuid: 50,
                title: 'Fund Reception',
                linkTitle: 'Fund Reception',
                url: '/shift/fund-reception',
                right: PermissionsEnum.ShiftManagement_Fund_Reception_Acknowledgement,
                hierarchy: 3,
            },
            {
                uuid: 51,
                title: 'Shift Compilation',
                linkTitle: 'Shift Compilation',
                url: '/shift/shift-compilation',
                right: PermissionsEnum.ShiftManagement_Shift_Compilation,
                hierarchy: 4,
            },
            {
                uuid: 52,
                title: 'All Shift Per Day',
                linkTitle: 'All Shift Per Day',
                url: '/shift/all-shift-per-day',
                right: PermissionsEnum.ShiftManagement_All_Shift_Per_Day_Report,
                hierarchy: 5,
            },
        ],
    },

    {
        uuid: 'Settings',
        title: 'Settings & Control',
        icon: 'fa fa-cogs',
        linkTitle: 'Settings & Control',
        hierarchy: 5,
        permissions: [
            {
                uuid: 53,
                title: 'User Manager',
                linkTitle: 'User Manager Setting',
                url: '/settings/user-management',
                right: PermissionsEnum.Settings_User_Manager,
                hierarchy: 1,
            },
            {
                uuid: 54,
                title: 'Role Manager',
                linkTitle: 'Role Manager Setting',
                url: '/settings/role-management',
                right: PermissionsEnum.Settings_Role_Manager,
                hierarchy: 2,
            },
            {
                uuid: 55,
                title: 'Seed Data Setup',
                linkTitle: 'Seed Data Setup',
                url: '/settings/seed-data',
                right: PermissionsEnum.Settings_Seed_Data_Setup,
                hierarchy: 3,
            },
            {
                uuid: 56,
                title: 'Global Settings',
                linkTitle: 'Global Setting & Control',
                url: '/settings/global-settings',
                right: PermissionsEnum.Settings_Global_Settings,
                hierarchy: 4,
            },
            {
                uuid: 57,
                title: 'Location Settings',
                linkTitle: 'Application Location Settings',
                url: '/settings/location-settings',
                right: PermissionsEnum.Settings_Location_Settings,
                hierarchy: 5,
            },
            {
                uuid: 58,
                title: 'Password Reset',
                linkTitle: 'Password Reset',
                url: '/settings/password-reset',
                right: PermissionsEnum.Settings_Password_Reset,
                hierarchy: 6,
            },
            {
                uuid: 61,
                title: 'Right Surveillance',
                linkTitle: 'Password Reset',
                url: '/settings/right-surveillance',
                right: PermissionsEnum.Settings_Right_Surveillance,
                hierarchy: 7,
            },
            {
                uuid: 59,
                title: 'Nhis Scheme Suspension',
                linkTitle: 'Batch Data Upload',
                url: '/settings/nhis-scheme-suspension',
                right: PermissionsEnum.Settings_Nhis_Scheme_Suspension,
                hierarchy: 8,
            },
            {
                uuid: 60,
                title: 'Ret Scheme Suspension',
                linkTitle: 'Password Reset',
                url: '/settings/ret-scheme-suspension',
                right: PermissionsEnum.Settings_Ret_Scheme_Suspension,
                hierarchy: 9,
            },
        ],
    },

    {
        uuid: 'Nurses',
        title: 'Nurses Section',
        icon: 'fa fa-heartbeat',
        linkTitle: 'Nurses Section',
        hierarchy: 6,
        permissions: [
            {
                uuid: 62,
                title: 'Vital Signs Capture',
                linkTitle: 'Vital Signs Capture',
                url: '/nurse/vital-signs-capture',
                right: PermissionsEnum.Nurses_Vital_Signs_Capture,
                hierarchy: 1,
            },
            {
                uuid: 62,
                title: 'Vital Signs Trend',
                linkTitle: 'Vital Signs Trend',
                url: '/nurse/vital-signs-trend',
                right: PermissionsEnum.Nurses_Vital_Signs_Trend,
                hierarchy: 2,
            },
            {
                uuid: 63,
                title: 'Nursing Note',
                linkTitle: 'Nursing Note',
                url: '/nurse/nursing-note',
                right: PermissionsEnum.Nurses_Nursing_Note,
                hierarchy: 3,
            },
            {
                uuid: 63,
                title: 'Nursing Care',
                linkTitle: 'Nursing Care',
                url: '/nurse/nursing-care',
                right: PermissionsEnum.Nurses_Nursing_Care,
                hierarchy: 4,
            },
            {
                uuid: 64,
                title: 'Drug Administration',
                linkTitle: 'Drug Administration',
                url: '/nurse/drug-administration',
                right: PermissionsEnum.Nurses_Drug_Administration,
                hierarchy: 5,
            },
            {
                uuid: 65,
                title: 'Nurse Patient e-Folder',
                linkTitle: 'Nurse Patient e-Folder',
                url: '/nurse/patient-e-folder',
                right: PermissionsEnum.Nurses_Nurse_Patient_eFolder,
                hierarchy: 6,
            },
            {
                uuid: 66,
                title: 'Nurses Antenatal Booking',
                linkTitle: 'Nurses Antenatal Booking',
                url: '/nurse/antenatal-booking',
                right: PermissionsEnum.Nurses_Nurse_Antenatal_Booking,
                hierarchy: 7,
            },
            {
                uuid: 67,
                title: 'Obstetrics History',
                linkTitle: 'Obstetrics History',
                url: '/nurse/obstetrics-history',
                right: PermissionsEnum.Nurses_Obstetrics_History,
                hierarchy: 8,
            },
            {
                uuid: 69,
                title: 'Anc Card Note',
                linkTitle: 'Anc Card Note',
                url: '/nurse/anc-card-note',
                right: PermissionsEnum.Nurses_Anc_Card_Note,
                hierarchy: 9,
            },
            {
                uuid: 68,
                title: 'Visual Acuity',
                linkTitle: 'Visual Acuity',
                url: '/nurse/visual-acuity',
                right: PermissionsEnum.Nurses_Visual_Acuity,
                hierarchy: 10,
            },
        ],
    },

    {
        uuid: 'Doctor',
        title: 'Clerking Interface',
        icon: 'fa fa-user-md',
        linkTitle: 'Clerking Interface Section',
        hierarchy: 7,
        permissions: [
            {
                uuid: 70,
                title: 'General Clerking Desk',
                linkTitle: 'Clerking Desk',
                url: '/clerking/general-clerking-desk',
                right: PermissionsEnum.Doctor_General_Clerking_Desk,
                hierarchy: 1,
            },
            {
                uuid: 71,
                title: 'Anc Clerking Desk',
                linkTitle: 'Anc Clerking Desk',
                url: '/clerking/anc-clerking',
                right: PermissionsEnum.Doctor_Anc_Clerking_Desk,
                hierarchy: 2,
            },
            {
                uuid: 72,
                title: 'Dental Clerking Desk',
                linkTitle: 'Dental Clerking Desk',
                url: '/clerking/dental-clerking-desk',
                right: PermissionsEnum.Doctor_Dental_Clerking_Desk,
                hierarchy: 3,
            },
            {
                uuid: 73,
                title: 'Physio Clerking Desk',
                linkTitle: 'Physio Clerking Desk',
                url: '/clerking/physio_clerking_desk',
                right: PermissionsEnum.Doctor_Physio_Clerking_Desk,
                hierarchy: 4,
            },
            {
                uuid: 74,
                title: 'Pediatrics Clerking Desk',
                linkTitle: 'Pediatrics Clerking Desk',
                url: '/clerking/pediatrics-clerking-desk',
                right: PermissionsEnum.Doctor_Pediatrics_Clerking_Desk,
                hierarchy: 5,
            },
            {
                uuid: 75,
                title: 'Doctor Patient e-Folder',
                linkTitle: 'Doctor Patient e-Folder',
                url: '/clerking/patient-e-folder',
                right: PermissionsEnum.Doctor_Doctor_Patient_eFolder,
                hierarchy: 6,
            },
            {
                uuid: 76,
                title: 'Inpatient Clerking',
                linkTitle: 'Inpatient Clerking',
                url: '/clerking/inpatient-clerking',
                right: PermissionsEnum.Doctor_Inpatient_Clerking,
                hierarchy: 7,
            },
            {
                uuid: 77,
                title: 'Antenatal Booking',
                linkTitle: 'Antenatal Booking',
                url: '/clerking/antenatal-booking',
                right: PermissionsEnum.Doctor_Patient_File_Upload,
                hierarchy: 8,
            },
            {
                uuid: 78,
                title: 'Patient File Upload',
                linkTitle: 'Patient File Upload',
                url: '/clerking/patient-file-upload',
                right: PermissionsEnum.Doctor_Doctor_Antenatal_Booking,
                hierarchy: 9,
            },
            {
                uuid: 79,
                title: 'General Outpatient Desk',
                linkTitle: 'General Outpatient Desk',
                url: '/clerking/general-outpatient-desk',
                right: PermissionsEnum.Doctor_General_Outpatient_Desk,
                hierarchy: 10,
            },
            {
                uuid: 80,
                title: 'Ophthalmology Clerking',
                linkTitle: 'Ophthalmology Clerking',
                url: '/clerking/ophthalmology-clerking',
                right: PermissionsEnum.Doctor_Ophthalmology_Clerking,
                hierarchy: 11,
            },
            {
                uuid: 81,
                title: 'Surgical Outpatient Consultation',
                linkTitle: 'Surgical Outpatient Consultation',
                url: '/clerking/surgical-outpatient-consultation',
                right: PermissionsEnum.Doctor_Surgical_Outpatient_Consultation,
                hierarchy: 12,
            },
            {
                uuid: 82,
                title: 'Hop Clinic Consultation',
                linkTitle: 'Hop Clinic Consultation',
                url: '/clerking/hop-clinic-consultation',
                right: PermissionsEnum.Doctor_Hop_Clinic_Consultation,
                hierarchy: 13,
            },
            {
                uuid: 83,
                title: 'Psychiatry Consultation',
                linkTitle: 'Psychiatry Consultation',
                url: '/clerking/psychiatry-consultation',
                right: PermissionsEnum.Doctor_Psychiatry_Consultation,
                hierarchy: 14,
            },
        ],
    },

    {
        uuid: 'LAB',
        title: 'Laboratory Section',
        icon: 'fa fa-flask',
        linkTitle: 'Laboratory Section',
        hierarchy: 8,
        permissions: [
            {
                uuid: 102,
                title: 'Lab Billing',
                linkTitle: 'Lab Billing',
                url: '/lab/lab-billing',
                right: PermissionsEnum.LAB_Billing,
                hierarchy: 1,
            },
            {
                uuid: 84,
                title: 'Specimen Collection',
                linkTitle: 'Specimen Collection',
                url: '/lab/specimen-collection',
                right: PermissionsEnum.LAB_Specimen_Collection,
                hierarchy: 2,
            },
            {
                uuid: 85,
                title: 'Specimen Acknowledgement',
                linkTitle: 'Specimen Collection Acknowledgement',
                url: '/lab/specimen-collection-acknowledgement',
                right: PermissionsEnum.LAB_Specimen_Collection_Acknowledgement,
                hierarchy: 3,
            },
            {
                uuid: 86,
                title: 'Lab Test Tracker',
                linkTitle: 'Lab Request Tracker',
                url: '/lab/lab-request-tracker',
                right: PermissionsEnum.LAB_Request_Tracker,
                hierarchy: 4,
            },
            {
                uuid: 102,
                title: 'Lab Parameter Registration',
                linkTitle: 'Lab Parameter Registration',
                url: '/lab/lab-param-registration',
                right: PermissionsEnum.LAB_Parameter_Registration,
                hierarchy: 5,
            },
            {
                uuid: 102,
                title: 'Lab RePush Samples',
                linkTitle: 'Lab RePush Samples',
                url: '/lab/lab-re-push-sample',
                right: PermissionsEnum.LAB_RePush_Samples,
                hierarchy: 6,
            },
            {
                title: 'General Medical Lab',
                uuid: 90,
                linkTitle: 'General Lab',
                url: '',
                right: PermissionsEnum.LAB_Medical_Microbiology,
                hasChild: true,
                show: false,
                hierarchy: 7,
                children: [
                    {
                        uuid: 202,
                        title: 'Parameter Setup',
                        linkTitle: 'Parameter Setup',
                        url: '/lab/medical-parameter-setup',
                        right: PermissionsEnum.LAB_MEDICAL_PARAM_SETUP,
                        hierarchy: 1,
                    },
                    {
                        uuid: 202,
                        title: 'Result Preparation',
                        linkTitle: 'Result Preparation',
                        url: '/lab/medical-lab-result-preparation',
                        right: PermissionsEnum.LAB_MEDICAL_RESULT_PREPARATION,
                        hierarchy: 2,
                    },
                    {
                        uuid: 202,
                        title: 'Lab Result View',
                        linkTitle: 'Lab Result View',
                        url: '/lab/medical-lab-result-view',
                        right: PermissionsEnum.LAB_MEDICAL_RESULT_VIEW,
                        hierarchy: 3,
                    },
                    {
                        uuid: 202,
                        title: 'Result Verification',
                        linkTitle: 'Result Verification',
                        url: '/lab/medical-lab-result-verification',
                        right: PermissionsEnum.LAB_MEDICAL_RESULT_VERIFICATION,
                        hierarchy: 4,
                    },
                    {
                        uuid: 202,
                        title: 'Pathologist Verification',
                        linkTitle: 'Pathologist Verification',
                        url: '/lab/medical-lab-pathologist-verification',
                        right: PermissionsEnum.LAB_MEDICAL_PATHOLOGIST_VERIFICATION,
                        hierarchy: 5,
                    },
                ],
            },
            {
                title: 'Microbiology Lab',
                uuid: 92,
                linkTitle: 'Microbiology Lab',
                url: '',
                right: PermissionsEnum.LAB_MICROBIOLOGY_MAIN,
                hasChild: true,
                show: false,
                hierarchy: 8,
                children: [
                    {
                        uuid: 202,
                        title: 'Result Control',
                        linkTitle: 'Result Control',
                        url: '/lab/micro-biology-result-control',
                        right: PermissionsEnum.LAB_MICROBIOLOGY_RESULT_CONTROL,
                        hierarchy: 3,
                    },
                    {
                        title: 'Serology / Molecular',
                        uuid: 92,
                        linkTitle: 'Serology / Molecular',
                        url: '',
                        right: PermissionsEnum.LAB_MICROBIOLOGY_SEROLOGY_MAIN,
                        hasChild: true,
                        show: false,
                        hierarchy: 4,
                        children: [
                            {
                                uuid: 202,
                                title: 'Result Preparation',
                                linkTitle: 'Result Preparation',
                                url: '/lab/micro-biology-serology-result-preparation',
                                right: PermissionsEnum.LAB_MICROBIOLOGY_SEROLOGY_RESULT_PREP,
                                hierarchy: 1,
                            },
                            {
                                uuid: 202,
                                title: 'Result Verification',
                                linkTitle: 'Result Verification',
                                url: '/lab/micro-biology-serology-result-verification',
                                right: PermissionsEnum.LAB_MICROBIOLOGY_SEROLOGY_RESULT_VERIFY,
                                hierarchy: 2,
                            },
                            {
                                uuid: 202,
                                title: 'Pathologist Verification',
                                linkTitle: 'Pathologist Verification',
                                url: '/lab/micro-biology-serology-pathologist-verification',
                                right: PermissionsEnum.LAB_MICROBIOLOGY_SEROLOGY_RESULT_PATH_VERIFY,
                                hierarchy: 3,
                            },
                        ],
                    },
                    {
                        title: 'Bacteriology / Parasitology',
                        uuid: 92,
                        linkTitle: 'Bacteriology / Parasitology',
                        url: '',
                        right: PermissionsEnum.LAB_MICROBIOLOGY_PARASITOLOGY_MAIN,
                        hasChild: true,
                        show: false,
                        hierarchy: 5,
                        children: [
                            {
                                uuid: 202,
                                title: 'Result Preparation',
                                linkTitle: 'Result Preparation',
                                url: '/lab/micro-biology-parasitology-result-preparation',
                                right: PermissionsEnum.LAB_MICROBIOLOGY_PARASITOLOGY_RESULT_PREP,
                                hierarchy: 1,
                            },
                            {
                                uuid: 202,
                                title: 'Result Verification',
                                linkTitle: 'Result Verification',
                                url: '/lab/micro-biology-parasitology-result-verification',
                                right: PermissionsEnum.LAB_MICROBIOLOGY_PARASITOLOGY_RESULT_VERIFY,
                                hierarchy: 2,
                            },
                            {
                                uuid: 202,
                                title: 'Pathologist Verification',
                                linkTitle: 'Pathologist Verification',
                                url: '/lab/micro-biology-parasitology-pathologist-verification',
                                right: PermissionsEnum.LAB_MICROBIOLOGY_PARASITOLOGY_RESULT_PATH_VERIFY,
                                hierarchy: 3,
                            },
                        ],
                    },
                ],
            },
            /*
            {
                title: 'Haematology Lab',
                uuid: 92,
                linkTitle: 'Haematology Lab',
                url: '',
                right: PermissionsEnum.LAB_HAEMATOLOGY_MAIN,
                hasChild: true,
                show: false,
                hierarchy: 9,
                children: [
                    {
                        uuid: 202,
                        title: 'Provisional Result Control',
                        linkTitle: 'Provisional Result Control',
                        url: '/lab/',
                        right: PermissionsEnum.LAB_HAEMATOLOGY_MAIN,
                        hierarchy: 1
                    },
                    {
                        uuid: 202,
                        title: 'Provisional Result',
                        linkTitle: 'Provisional Result',
                        url: '/lab/',
                        right: PermissionsEnum.LAB_HAEMATOLOGY_MAIN,
                        hierarchy: 2
                    },
                    {
                        uuid: 202,
                        title: 'Bone Marrow Result',
                        linkTitle: 'Bone Marrow Result',
                        url: '/lab/',
                        right: PermissionsEnum.LAB_HAEMATOLOGY_MAIN,
                        hierarchy: 3
                    },
                ],
            },
            {
                title: 'Chemical Lab',
                uuid: 92,
                linkTitle: 'Chemical Lab',
                url: '',
                right: PermissionsEnum.LAB_HAEMATOLOGY_MAIN,
                hasChild: true,
                show: false,
                hierarchy: 10,
                children: [
                    {
                        uuid: 202,
                        title: 'Provisional Result Control',
                        linkTitle: 'Provisional Result Control',
                        url: '/lab/',
                        right: PermissionsEnum.LAB_HAEMATOLOGY_MAIN,
                        hierarchy: 1
                    },
                    {
                        uuid: 202,
                        title: 'Provisional Result',
                        linkTitle: 'Provisional Result',
                        url: '/lab/',
                        right: PermissionsEnum.LAB_HAEMATOLOGY_MAIN,
                        hierarchy: 2
                    },
                    {
                        uuid: 202,
                        title: 'Bone Marrow Result',
                        linkTitle: 'Bone Marrow Result',
                        url: '/lab/',
                        right: PermissionsEnum.LAB_HAEMATOLOGY_MAIN,
                        hierarchy: 3
                    },
                ],
            },
            {
                title: 'Anatomical Lab',
                uuid: 92,
                linkTitle: 'Anatomical Lab',
                url: '',
                right: PermissionsEnum.LAB_HAEMATOLOGY_MAIN,
                hasChild: true,
                show: false,
                hierarchy: 11,
                children: [
                    {
                        uuid: 202,
                        title: 'Gross / Macroscopy',
                        linkTitle: 'Gross / Macroscopy',
                        url: '/lab/',
                        right: PermissionsEnum.LAB_MICROBIOLOGY_RESULT_CONTROL,
                        hierarchy: 1
                    },
                    {
                        uuid: 202,
                        title: 'Lab Process',
                        linkTitle: 'Lab Process',
                        url: '/lab/',
                        right: PermissionsEnum.LAB_MICROBIOLOGY_RESULT_CONTROL,
                        hierarchy: 2
                    },
                    {
                        uuid: 202,
                        title: 'Quality Control',
                        linkTitle: 'Quality Control',
                        url: '/lab/',
                        right: PermissionsEnum.LAB_MICROBIOLOGY_RESULT_CONTROL,
                        hierarchy: 3
                    },
                    {
                        uuid: 202,
                        title: 'SFA',
                        linkTitle: 'SFA',
                        right: PermissionsEnum.LAB_HAEMATOLOGY_MAIN,
                        hierarchy: 4,
                        hasChild: true,
                        show: false,
                        children: [
                            {
                                uuid: 202,
                                title: 'SFA Result Prep',
                                linkTitle: 'SFA Result Prep',
                                url: '/lab/',
                                right: PermissionsEnum.LAB_MICROBIOLOGY_SEROLOGY_RESULT_PREP,
                                hierarchy: 1
                            },
                            {
                                uuid: 202,
                                title: 'SFA Result Veri',
                                linkTitle: 'SFA Result Veri',
                                url: '/lab/',
                                right: PermissionsEnum.LAB_MICROBIOLOGY_SEROLOGY_RESULT_PREP,
                                hierarchy: 2
                            },
                            {
                                uuid: 202,
                                title: 'SFA Pathologist Veri',
                                linkTitle: 'SFA Pathologist Veri',
                                url: '/lab/',
                                right: PermissionsEnum.LAB_MICROBIOLOGY_SEROLOGY_RESULT_PREP,
                                hierarchy: 2
                            },
                        ],
                    },
                ],
            },
            */
        ],
    },

    {
        uuid: 'Radiology',
        title: 'Radiology',
        icon: 'fa fa-podcast',
        linkTitle: 'Radiology Section',
        hierarchy: 9,
        permissions: [
            {
                uuid: 91,
                title: 'Radiology Billing',
                linkTitle: 'Radiology Billing',
                url: '/radiology/radiology-billing',
                right: PermissionsEnum.Radiology_Radiology_Billing,
                hierarchy: 1,
            },
            {
                uuid: 95,
                title: 'Radiology Result Preparation',
                linkTitle: 'Radiology Result Preparation',
                url: '/radiology/result-preparation',
                right: PermissionsEnum.Radiology_Radiology_Result_Preparation,
                hierarchy: 2,
            },
            {
                uuid: 92,
                title: 'Radiology Result Verification',
                linkTitle: 'Radiology Result Verification',
                url: '/radiology/result-verification',
                right: PermissionsEnum.Radiology_Radiology_Result_Verification,
                hierarchy: 3,
            },
            {
                uuid: 93,
                title: 'Radiology Result View',
                linkTitle: 'Radiology Result View',
                url: '/radiology/radiology-result-view',
                right: PermissionsEnum.Radiology_Radiology_Result_View,
                hierarchy: 4,
            },
            {
                uuid: 94,
                title: 'Provisional Result View',
                linkTitle: 'Provisional Result View',
                url: '/radiology/provisional-result-view',
                right: PermissionsEnum.Radiology_Radiology_Provisional_Result_View,
                hierarchy: 5,
            },
            {
                uuid: 104,
                title: 'Radiology Request Tracker',
                linkTitle: 'Radiology Request Tracker',
                url: '/radiology/radiology-request-tracker',
                right: PermissionsEnum.Radiology_Radiology_Request_Tracker,
                hierarchy: 6,
            },
            {
                uuid: 105,
                title: 'Radiology Draft',
                linkTitle: 'Radiology Draft',
                url: '/radiology/radiology-draft',
                right: PermissionsEnum.Radiology_Radiology_Draft,
                hierarchy: 7,
            },
        ],
    },

    {
        uuid: 'Other',
        title: 'Extras & Defaults',
        icon: 'fa fa-hospital',
        linkTitle: 'Extras & Others',
        hierarchy: 10,
        permissions: [
            {
                uuid: 96,
                title: 'Add Products or Services',
                linkTitle: 'Service Register',
                url: '/others/service-register',
                right: PermissionsEnum.Other_Service_Register,
                hierarchy: 1,
            },
            {
                uuid: 102,
                title: 'Scheme Service Price',
                linkTitle: 'Scheme Service Price',
                url: '/others/scheme-service-price',
                right: PermissionsEnum.Other_Scheme_Service_Price,
                hierarchy: 2,
            },
            {
                uuid: 97,
                title: 'Track A Request',
                linkTitle: 'Request Tracker',
                url: '/others/request-tracker',
                right: PermissionsEnum.Other_Request_Tracker,
                hierarchy: 3,
            },
            {
                uuid: 98,
                title: 'Manage Vendors',
                linkTitle: 'Vendor Management',
                url: '/others/vendor-management',
                right: PermissionsEnum.Other_Vendor_Management,
                hierarchy: 4,
            },
            {
                uuid: 101,
                title: 'Dashboard View',
                linkTitle: 'Dashboard View',
                url: '/others/dashboard',
                right: PermissionsEnum.Other_Dashboard,
                hierarchy: 5,
            },
        ],
    },

    {
        uuid: 'settlement',
        title: 'Resolution',
        icon: 'fa fa-handshake',
        linkTitle: 'Resolution Section ',
        hierarchy: 11,
        permissions: [
            {
                uuid: 99,
                title: 'Service Provider Invoice',
                linkTitle: 'Service Provider Invoice',
                url: '/settlement/service-provider-invoice',
                right: PermissionsEnum.Settlement_Service_Provider_Invoice,
                hierarchy: 1,
            },
            {
                uuid: 100,
                title: 'Settlement Advice',
                linkTitle: 'Settlement Advice',
                url: '/settlement/settlement-advice',
                right: PermissionsEnum.Settlement_Settlement_Advice,
                hierarchy: 2,
            },
        ],
    },

    {
        uuid: 'Report',
        title: 'Reports Preview',
        icon: 'fa fa-notes-medical',
        linkTitle: 'Reports Preview',
        hierarchy: 12,
        permissions: [
            {
                title: 'EMR Reports',
                uuid: 201,
                linkTitle: 'Medical Record Reports',
                url: '',
                hasChild: true,
                show: false,
                hierarchy: 1,
                children: [
                    {
                        uuid: 199,
                        title: 'Registered Patient Report',
                        linkTitle: 'Registered Patient Report',
                        url: '/reports/registered-patient-report',
                        right: PermissionsEnum.Reports_Registered_Patient,
                        hierarchy: 1,
                    },
                    {
                        uuid: 203,
                        title: 'Appointment Booking',
                        linkTitle: 'Appointment Booking Report',
                        url: '/reports/appointment-booking-report',
                        right: PermissionsEnum.Reports_Appointment_Booking,
                        hierarchy: 2,
                    },
                    {
                        uuid: 202,
                        title: 'Admission Register Report',
                        linkTitle: 'Admission Register Report',
                        url: '/reports/admission-register-report',
                        right: PermissionsEnum.Reports_Admission_Register,
                        hierarchy: 3,
                    },
                    {
                        uuid: 202,
                        title: 'Patient E-Folder',
                        linkTitle: 'Patient E-Folder',
                        url: '/reports/patient-e-folder',
                        right: PermissionsEnum.Reports_Patient_E_Folder,
                        hierarchy: 4,
                    },
                    {
                        title: 'Patient Interim Invoice',
                        linkTitle: 'Patient Interim Invoice',
                        url: '/reports/patient-interim-invoice',
                        right: PermissionsEnum.Reports_Emr_Patient_Interim_Invoice,
                        hierarchy: 5,
                    },
                ],
            },
            {
                title: 'Pharmacy Reports',
                uuid: 201,
                linkTitle: 'All Pharmacy Reports',
                url: '',
                right: PermissionsEnum.Reports_Daily_Cash_Collection,
                hasChild: true,
                show: false,
                hierarchy: 2,
                children: [
                    {
                        uuid: 202,
                        title: 'Stock BalancePerOutlet',
                        linkTitle: 'Stock Balance Per Outlet',
                        url: '/reports/stock-balance-per-outlet',
                        right: PermissionsEnum.Reports_Stock_Balance_Per_Outlet,
                        hierarchy: 1,
                    },
                    {
                        uuid: 202,
                        title: 'Outlet Activity Report',
                        linkTitle: 'Outlet Activity Report',
                        url: '/reports/outlet-activity-report',
                        right: PermissionsEnum.Reports_Outlet_Activity_Report,
                        hierarchy: 2,
                    },
                ],
            },
            {
                title: 'Account Reports',
                uuid: 201,
                linkTitle: 'All Accounting Reports',
                url: '',
                right: PermissionsEnum.Reports_Daily_Cash_Collection,
                hasChild: true,
                show: false,
                hierarchy: 3,
                children: [
                    {
                        uuid: 202,
                        title: 'ShiftPerDay Report',
                        linkTitle: 'All Shift Per Day',
                        url: '/reports/all-shift-per-day',
                        right: PermissionsEnum.Reports_All_Shift_Per_Day,
                        hierarchy: 1,
                    },
                    {
                        uuid: 202,
                        title: 'Daily Collection Report',
                        linkTitle: 'daily cash collection',
                        url: '/reports/daily-cash-collection',
                        right: PermissionsEnum.Reports_Daily_Cash_Collection,
                        hierarchy: 2,
                    },
                    {
                        uuid: 202,
                        title: 'Cancelled Receipts Report',
                        linkTitle: 'Cancelled Receipts Report',
                        url: '/reports/cancelled-receipt-report',
                        right: PermissionsEnum.Reports_Cancelled_Receipts,
                        hierarchy: 3,
                    },
                    {
                        uuid: 202,
                        title: 'Payment Receipt Report',
                        linkTitle: 'Payment Receipt Report',
                        url: '/reports/payment-receipt-report',
                        right: PermissionsEnum.Reports_Payment_Receipt_Report,
                        hierarchy: 4,
                    },
                    {
                        title: 'Scheme Consumption',
                        linkTitle: 'Scheme Consumption Report',
                        url: '/reports/scheme-consumption-report',
                        right: PermissionsEnum.Reports_Account_Scheme_Consumption,
                        hierarchy: 5,
                    }
                ],
            },
            {
                title: 'Other Reports',
                linkTitle: 'Other Reports',
                hasChild: true,
                show: false,
                hierarchy: 4,
                children: [
                    {
                        uuid: 202,
                        title: 'Service Charge Report',
                        linkTitle: 'Service Charge Report',
                        url: '/reports/other-service-charge-report',
                        right: PermissionsEnum.Reports_Other_Service_Charge,
                        hierarchy: 1,
                    },
                ],
            },
        ],
    },
];
