export enum PermissionsEnum {
    Emr_Patient_Registration = 'Access_Patient_Registration',
    Emr_Edit_Patient_Details = 'Access_Edit_Patient_Details',
    Emr_Record_Visit = 'Access_Record_Visit',
    Emr_Patient_Folder_Movement = 'Access_Patient_Folder_Movement',
    Emr_Patient_Category_Management = 'Access_Patient_Category_Management',
    Emr_Edit_Scheme_Details = 'Access_Edit_Scheme_Details',
    Emr_Patient_Admission = 'Access_Patient_Admission',
    Emr_Admission_Details = 'Access_Admission_Details',
    Emr_Ward_Transfer = 'Access_Ward_Transfer',
    Emr_Coding_and_Indexing = 'Access_Coding_and_Indexing',
    Emr_Appointment_Booking = 'Access_Appointment_Booking',
    Emr_Appointment_Booking_Setup = 'Access_Appointment_Booking_Setup',
    Emr_Clinical_Attendance = 'Access_Clinical_Attendance',
    Emr_Death_Register = 'Access_Death_Register',
    Emr_Patient_Discharge = 'Access_Patient_Discharge',
    Emr_Approval_Code_Office = 'Access_Approval_Code_Office',
    Emr_Birth_Register = 'Access_Birth_Register',
    Emr_Patient_Search_Index = 'Access_Patient_Search_Index',
    Emr_Edit_Organization_Details = 'Access_Edit_Organization_Details',

    Pharmacy_Drug_Register = 'Access_Drug_Register',
    Pharmacy_Pharmacy_Billing = 'Access_Pharmacy_Billing',
    Pharmacy_Drug_Order = 'Access_Drug_Order',
    Pharmacy_Receive_Goods_From_Suppliers = 'Access_Receive_Goods_From_Suppliers',
    Pharmacy_Outlet_Reconciliation = 'Access_Outlet_Reconciliation',
    Pharmacy_Store_Reconciliation = 'Access_Store_Reconciliation',
    Pharmacy_To_Store_Requisition = 'Access_To_Store_Requisition',
    Pharmacy_To_Outlet_Requisition = 'Access_To_Outlet_Requisition',
    Pharmacy_Store_Issuance = 'Access_Store_Issuance',
    Pharmacy_Outlet_Issuance = 'Access_Outlet_Issuance',
    Pharmacy_Drug_Dispensing = 'Access_Drug_Dispensing',
    Pharmacy_Batch_Drug_Dispensing = 'Access_Batch_Drug_Dispensing',
    Pharmacy_Drug_Withdrawals = 'Access_Drug_Withdrawals',
    Pharmacy_Patient_Drug_Return = 'Access_Patient_Drug_Return',
    Pharmacy_Drug_Return_Note = 'Access_Drug_Return_Note',
    Pharmacy_Private_Wing_Pharmacy_Billing = 'Access_Private_Wing_Pharmacy_Billing',
    Pharmacy_Executive_Wing_Pharmacy_Billing = 'Access_Executive_Wing_Pharmacy_Billing',
    Pharmacy_Pharmacy_Notifications = 'Access_Pharmacy_Notifications',

    Billing_Patient_Billing = 'Access_Patient_Billing',
    Billing_Patient_Scheme_Billing = 'Access_Patient_Scheme_Billing',
    Billing_Bill_Adjustment = 'Access_Bill_Adjustment',
    Billing_Payment_Manager = 'Access_Payment_Manager',
    Billing_Patient_Deposit = 'Access_Patient_Deposit',
    Billing_Bill_Waivers = 'Access_Bill_Waivers',
    Billing_Receipt_Cancellation = 'Access_Receipt_Cancellation',
    Billing_Hmo_Billing = 'Access_Hmo_Billing',
    Billing_Ret_Organization_Billing = 'Access_Ret_Organization_Billing',
    Billing_Scheme_Bill_Adjustment = 'Access_Scheme_Bill_Adjustment',
    Billing_Refund = 'Access_Refund',
    Billing_Patient_Deposit_Transfer = 'Access_Patient_Deposit_Transfer',

    ShiftManagement_Shift_Manager = 'Access_Shift_Manager',
    ShiftManagement_Cashier_Shift_Report = 'Access_Cashier_Shift_Report',
    ShiftManagement_Fund_Reception_Acknowledgement = 'Access_Fund_Reception_Acknowledgement',
    ShiftManagement_Shift_Compilation = 'Access_Shift_Compilation',
    ShiftManagement_All_Shift_Per_Day_Report = 'Access_All_Shift_Per_Day_Report',

    Settings_User_Manager = 'Access_User_Manager',
    Settings_Role_Manager = 'Access_Role_Manager',
    Settings_Seed_Data_Setup = 'Access_Seed_Data_Setup',
    Settings_Global_Settings = 'Access_Global_Settings',
    Settings_Location_Settings = 'Access_Location_Settings',
    Settings_Password_Reset = 'Access_Password_Reset',
    Settings_Nhis_Scheme_Suspension = 'Access_Nhis_Scheme_Suspension',
    Settings_Ret_Scheme_Suspension = 'Access_Ret_Scheme_Suspension',
    Settings_Right_Surveillance = 'Access_Right_Surveillance',

    Nurses_Vital_Signs_Capture = 'Access_Vital_Signs_Capture',
    Nurses_Vital_Signs_Trend = 'Access_Vital_Signs_Trend',
    Nurses_Nursing_Note = 'Access_Nursing_Note',
    Nurses_Nursing_Care = 'Access_Nursing_Care',
    Nurses_Drug_Administration = 'Access_Drug_Administration',
    Nurses_Nurse_Patient_eFolder = 'Access_Nurse_Patient_eFolder',
    Nurses_Nurse_Antenatal_Booking = 'Access_Nurse_Antenatal_Booking',
    Nurses_Obstetrics_History = 'Access_Obstetrics_History',
    Nurses_Anc_Booking = 'Access_Anc_Booking',
    Nurses_Anc_Card_Note = 'Access_Anc_Card_Note',
    Nurses_Visual_Acuity = 'Access_Nurse_Visual_Acuity',

    Doctor_General_Clerking_Desk = 'Access_General_Clerking_Desk',
    Doctor_Anc_Clerking_Desk = 'Access_Anc_Clerking_Desk',
    Doctor_Dental_Clerking_Desk = 'Access_Dental_Clerking_Desk',
    Doctor_Physio_Clerking_Desk = 'Access_Physio_Clerking_Desk',
    Doctor_Pediatrics_Clerking_Desk = 'Access_Pediatrics_Clerking_Desk',
    Doctor_Doctor_Patient_eFolder = 'Access_Doctor_Patient_eFolder',
    Doctor_Inpatient_Clerking = 'Access_Inpatient_Clerking',
    Doctor_Patient_File_Upload = 'Access_Patient_File_Upload',
    Doctor_Doctor_Antenatal_Booking = 'Access_Doctor_Antenatal_Booking',
    Doctor_General_Outpatient_Desk = 'Access_General_Outpatient_Desk',
    Doctor_Ophthalmology_Clerking = 'Access_Ophthalmology_Clerking',
    Doctor_Surgical_Outpatient_Consultation = 'Access_Surgical_Outpatient_Consultation',
    Doctor_Hop_Clinic_Consultation = 'Access_Hop_Clinic_Consultation',
    Doctor_Psychiatry_Consultation = 'Access_Psychiatry_Consultation',

    LAB_Specimen_Collection = 'Access_Specimen_Collection',
    LAB_Specimen_Collection_Acknowledgement = 'Access_Specimen_Collection_Acknowledgement',
    LAB_Request_Tracker = 'Access_Lab_Request_Tracker',
    LAB_Billing = 'Access_Lab_Billing',
    LAB_Parameter_Registration = 'Access_Lab_Parameter_Registration',
    LAB_RePush_Samples = 'Access_Lab_Re_Push_Sample',
    LAB_Chemical_Laboratory = 'Access_Chemical_Laboratory',
    LAB_Anatomical_Laboratory = 'Access_Anatomical_Laboratory',
    LAB_Haematology = 'Access_Haematology',
    // MEDICAL LAB SUBMODULES
    LAB_Medical_Microbiology = 'Access_Medical_Microbiology',
    LAB_MEDICAL_PARAM_SETUP = 'Access_Medical_Param_Setup',
    LAB_MEDICAL_RESULT_VIEW = 'Access_Medical_Result_View',
    LAB_MEDICAL_ORIGINAL_RESULT_VIEW = 'Access_Medical_Original_Result_View',
    LAB_MEDICAL_PROVISIONAL_RESULT_VIEW = 'Access_Medical_Provisional_Result',
    LAB_MEDICAL_PROVISIONAL_RESULT_CONTROL = 'Access_Medical_Provisional_Result_Control',
    LAB_MEDICAL_RESULT_PREPARATION = 'Access_Medical_Result_Preparation',
    LAB_MEDICAL_RESULT_VERIFICATION = 'Access_Medical_Result_Verification',
    LAB_MEDICAL_PATHOLOGIST_VERIFICATION = 'Access_Medical_Pathologist_Verification',
    // MICROBIOLOGY
    LAB_MICROBIOLOGY_MAIN = 'Access_Microbiology_Main',
    LAB_MICROBIOLOGY_PARAM_SETUP = 'Access_Microbiology_Param_Setup',
    LAB_MICROBIOLOGY_RESULT_VIEW = 'Access_Microbiology_Result_View',
    LAB_MICROBIOLOGY_RESULT_CONTROL = 'Access_Microbiology_Result_Control',
    // MICROBIOLOGY SEROLOGY
    LAB_MICROBIOLOGY_SEROLOGY_MAIN = 'Access_Microbiology_Serology_Main',
    LAB_MICROBIOLOGY_SEROLOGY_RESULT_PREP = 'Access_Microbiology_Serology_Result_Prep',
    LAB_MICROBIOLOGY_SEROLOGY_RESULT_VERIFY = 'Access_Microbiology_Serology_Result_Verify',
    LAB_MICROBIOLOGY_SEROLOGY_RESULT_PATH_VERIFY = 'Access_Microbiology_Serology_Path_Result_Verify',
    // MICROBIOLOGY PARASITOLOGY
    LAB_MICROBIOLOGY_PARASITOLOGY_MAIN = 'Access_Microbiology_Parasitology_Main',
    LAB_MICROBIOLOGY_PARASITOLOGY_RESULT_PREP = 'Access_Microbiology_Parasitology_Result_Prep',
    LAB_MICROBIOLOGY_PARASITOLOGY_RESULT_VERIFY = 'Access_Microbiology_Parasitology_Result_Verify',
    LAB_MICROBIOLOGY_PARASITOLOGY_RESULT_PATH_VERIFY = 'Access_Microbiology_Parasitology_Path_Result_Verify', // Pathologist Verification
    // HAEMATOLOGY
    LAB_HAEMATOLOGY_MAIN = 'Access_Haematology_Main',

    Radiology_Radiology_Result_Preparation = 'Access_Radiology_Result_Preparation',
    Radiology_Radiology_Result_Verification = 'Access_Radiology_Result_Verification',
    Radiology_Radiology_Result_View = 'Access_Radiology_Result_View',
    Radiology_Radiology_Provisional_Result_View = 'Access_Radiology_Provisional_Result_View',
    Radiology_Radiology_Billing = 'Access_Radiology_Billing',
    Radiology_Radiology_Request_Tracker = 'Access_Radiology_Request_Tracker',
    Radiology_Radiology_Draft = 'Access_Radiology_Draft',

    Other_Request_Tracker = 'Access_Request_Tracker',
    Other_Vendor_Management = 'Access_Vendor_Management',
    Other_Service_Register = 'Access_Service_Register',
    Other_Dashboard = 'Access_Other_Dashboard',
    Other_Scheme_Service_Price = 'Access_Other_Scheme_Service_Price',

    Settlement_Service_Provider_Invoice = 'Access_Service_Provider_Invoice',
    Settlement_Settlement_Advice = 'Access_Settlement_Advice',

    Reports_Registered_Patient = 'Access_Reports_Registered_Patient',
    Reports_Appointment_Booking = 'Access_Reports_Appointment_Booking',
    Reports_Admission_Register = 'Access_Reports_Admission_Register',
    Reports_All_Shift_Per_Day = 'Access_Reports_All_Shift_Per_Day',
    Reports_Daily_Cash_Collection = 'Access_Reports_Daily_Cash_Collection',
    Reports_Cancelled_Receipts = 'Access_Reports_Cancelled_Receipts',
    Reports_Payment_Receipt_Report = 'Access_Reports_Payment_Receipt_Report',
    Reports_Stock_Balance_Per_Outlet = 'Access_Reports_Stock_Balance_Per_Outlet',
    Reports_Outlet_Activity_Report = 'Access_Reports_Outlet_Activity_Report',
    Reports_Patient_E_Folder = 'Access_Reports_Patient_E_Folder',
    Reports_Emr_Patient_Interim_Invoice = 'Access_Reports_Emr_Patient_Interim_Invoice',
    Reports_Account_Scheme_Consumption = 'Access_Reports_Scheme_Consumption_Report',

    Reports_Other_Service_Main = 'Access_Reports_Other_Service_Main',
    Reports_Other_Service_Charge = 'Access_Reports_Other_Service_Entire_Charge',

}

export enum ModuleNamesEnum {
    EMR = 'EMR',
    PHARMACY = 'Pharmacy',
    BILLING = 'Billing',
    SHIFT_MANAGEMENT = 'ShiftManagement',
    SETTINGS = 'Settings',
    NURSING = 'Nurses',
    DOCTOR = 'Doctor',
    LAB = 'LAB',
    RADIOLOGY = 'Radiology',
    OTHER = 'Other',
    SETTLEMENT = 'Settlement',
}
