export enum ServiceUsageEnum {
    REGISTRATION = 'REGISTRATION',
    REVISIT = 'REVISIT',
    CONSULTATION = 'CONSULTATION',
    ADMISSION = 'ADMISSION',
    BED_SPACE = 'BED SPACE',
    ACCOMMODATION = 'ACCOMMODATION',
    CARDS_AND_FOLDERS = 'CARDS AND FOLDERS',
    DEPOSIT_FUNDS = 'DEPOSIT FUNDS',
    INPATIENT_SERVICES = 'INPATIENT SERVICES',
    LABORATORY_SERVICES = 'LABORATORY SERVICES',
}
