package com.hmis.server.hmis.modules.pharmacy.dto;

public enum DrugColumnEnum {
	GENERIC,
	DESCRIPTION,
	BRAND,
	STRENGTH,
	COST_PRICE,
	UNIT_OF_ISSUE,
	PACKS_PER_PACKING_UNIT,
	UNIT_COST_PRICE,
	GENERAL_MARK_UP,
	REGULAR_SELLING_PRICE,
	NHIS_SELLING_PRICE,
	CLASSIFICATION,
	FORMULATION

}
