package com.hmis.server.hmis.modules.clearking.dto;

public enum ClerkPatientActivityEnum {
    VITAL_SIGN,
    CONSULTATION,
    OPERATION_NOTE,
    WARD_TRANSFER,
    CLINIC_TRANSFER,
    NURSE_NOTE,
    DIAGNOSIS,
    UPLOAD_FILES,
    ANC_FOLLOW_UP_VISIT,
    DRUG_CHART,
    DRUG_REQUEST,
    LAB_REQUEST,
    RADIOLOGY_REQUEST,
    PROCEDURE_REPORT,
    RADIOLOGY_REPORT,
    LAB_RESULT,
    OBSTETRICS_HISTORY
}
